name: Secrets
on: push
jobs:
  print:
    runs_on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"